Moving code around. Finalizing documentation. Clean up.

diff --git a/ascent b/ascent
--- a/ascent
+++ b/ascent
@@ -54,8 +54,13 @@ print_help() {
         echo -e "#################################################################${NC}"
 }
 
-# a bit OOP'ish to not care about whether serial or number has to be passed
-# when complete line from config is saved.
+# Kind of OOP'ish approach to not care about whether serial or number has to
+# be passed. Thus enabling a smooth interactive mode by only specifying $d0
+# or $d1 and not its serial or number, which would look like:
+#
+#      $ source ascent.sh
+#      $ call $d0_serial $d1_number
+
 number_of() {
 	echo "$1" | cut -d "$DELIMITER" -f3
 }
@@ -80,8 +85,8 @@ B="\033[0;35m"
 Y="\033[1;33m"
 GRAY="\033[0;37m"
 
-# only one character is allowed in fact of using cut,
-# please allign your config file accordingly.
+# Feel free to change, but only one character is allowed in fact of using cut.
+# Remmber to allign config file accordingly after changing delimiter.
 DELIMITER="="
 
 # default directory is the current working directory
@@ -89,9 +94,9 @@ ASCENT_CONFIG="$(pwd)/ascent.cfg"
 ASCENT_VERSION="0.1"
 
 sanity() {
-
 	echo
 	echo -e "${Y}[SANITY_CHECK] can config be found?${NC}"
+
 	if [ ! -f "$ASCENT_CONFIG" ]; then
 		echo
 		echo -e "${R}[ERROR] No config file found! Please provide one in current working "
@@ -102,19 +107,18 @@ sanity() {
 		export ASCENT_CONFIG=""
 		return 1
 	else
-		# parsing config file
-		d0="$(cat "$ASCENT_CONFIG" | grep device_0 )"
-		d1="$(cat "$ASCENT_CONFIG" | grep device_1 )"
-		# check whether holds content, otherwise following check would succeed in
-		# case of an empty file.
-		if [ ${#d0} -gt 10 ] && [ ${#d1} -gt 10 ]; then
+		# parsing config
+		d0="$(cat "$ASCENT_CONFIG" | grep device_0= )"
+		d1="$(cat "$ASCENT_CONFIG" | grep device_1= )"
+		# check (unprecisely) whether d0 and d1 hold "enough" information
+		if [ ${#d0} -gt 20 ] && [ ${#d1} -gt 20 ]; then
 			echo -e "${G}[INFO] config $ASCENT_CONFIG has been parsed:${NC}"
 			cat "$ASCENT_CONFIG"
 			echo
 		else
-			echo -e "${R}[ERROR] content of config file seems corrupted,"
-			echo -e "        thus it could not been parsed."
-			echo -e "        content of config file:${NC}"
+			echo
+			echo -e "${R}[ERROR] content of config file seems corrupted, thus it could"
+			echo -e "        not been parsed. Content of config file:${NC}"
 			cat "$ASCENT_CONFIG"
 			echo
 			return 1
@@ -138,103 +142,8 @@ sanity() {
 	fi
 }
 
-#  test wrapper
-2g() {
-	sms
-	call
-}
-
-3g() {
-	2g
-	data
-}
-
-sms() {
-	if [ $# -eq 2 ]; then
-		send_sms "$1" "$2"
-	else
-		send_sms "$d0" "$d1"
-		send_sms "$d1" "$d0"
-	fi
-}
-
-call() {
-	if [ $# -eq 2 ]; then
-		do_call "$1" "$2"
-	else
-		do_call "$d0" "$d1"
-		do_call "$d1" "$d0"
-	fi
-}
-
-data() {
-		ping "$d0" "8.8.8.8"
-		ping "$d1" "8.8.8.8"
-}
-
-ping() {
-	echo -e "${Y}[TEST-DATA] ${G}$1${Y} tries to ping ${G}$2${Y} ${NC}"
-	adb -s "$(serial_of "$1")" shell ping -c 3 "$2"
-}
-
-# interactive print_helpers (debugging)
-
-d0() {
-	echo $d0
-}
-
-d1() {
-	echo $d1
-}
-
-adb0() {
-	adb -s "$(serial_of $d0)" $@
-}
-
-adb1() {
-	adb -s "$(serial_of $d1)" $@
-}
-
-go_to_homescreen() {
-	adb -s "$(serial_of "$d0")" shell input keyevent "$KEYCODE_HOME"
-	adb -s "$(serial_of "$d1")" shell input keyevent "$KEYCODE_HOME"
-}
-
-# unlock_device() expects that there is no password or pattern to unlock the phone.
-# (A straight swipe from bottom to center should unlock the phone.)
-unlock_device() {
-	if [ $# -ne 1 ]; then
-		echo
-		echo -e "${R}[ERROR] You must specify which device (\$d0||\$d1) should be unlocked!"
-		echo
-		return 1
-	fi
-
-	screen="$(adb -s $(serial_of $1) shell dumpsys display | grep deviceWidth \
-		| awk -F"deviceWidth=" '{print $2}' | head -n 1)"
-
-	width="$(echo $screen | cut -d ',' -f1)"
-	height="$(echo $screen | cut -d '=' -f2 | cut -d '}' -f1)"
-
-	# swipe coordinates - from bottom to center
-	x=$((width/2))
-	y1=$((height-20))
-	y2=$((height/2))
-
-	adb -s "$(serial_of $1)" shell input keyevent "$KEYCODE_POWER"
-	sleep 1
-	adb -s "$(serial_of $1)" shell input swipe "$x" "$y1" "$x" "$y2"
-}
-
-# actual tests
+# test functions
 send_sms() {
-	if [ $# -ne 2 ]; then
-		echo -e "${R}[ERROR] You need to pass 2 arguments to send_sms()"
-		echo
-		echo "	send_sms \$sender_serial \$receiver_number ${NC}"
-		echo
-		exit 1
-	fi
 
 	go_to_homescreen
 	echo -e "$Y[TEST-SMS] ${G}$1${Y} sends SMS to ${G}$2${Y} ${NC}"
@@ -274,43 +183,127 @@ do_call() {
 		echo -e "${Y}	[INFO] ${G}$1${Y} ends call ${NC}"
 		adb -s "$(serial_of "$1")" shell  input keyevent "$KEYCODE_ENDCALL"
 	fi
+
 	go_to_homescreen
 	echo
 }
 
+#  test wrapper
+2g() {
+	sms
+	call
+}
 
-# check if config file is passed or user request man page?
-if [ "$1" = "-c" ]; then
-	# simply export ASCENT_CONFIG sanity() will take care about wrong config
-	export ASCENT_CONFIG="$2"
-	if [ -f "$2" ]; then
-		shift 2
+3g() {
+	2g
+	data
+}
+
+sms() {
+	if [ $# -eq 2 ]; then
+		send_sms "$1" "$2"
+	else
+		send_sms "$d0" "$d1"
+		send_sms "$d1" "$d0"
 	fi
-elif [[ "$1" == *"help"* ]]; then
+}
+
+call() {
+	if [ $# -eq 2 ]; then
+		do_call "$1" "$2"
+	else
+		do_call "$d0" "$d1"
+		do_call "$d1" "$d0"
+	fi
+}
+
+data() {
+	ping "$d0" 8.8.8.8
+  ping "$d1" 8.8.8.8
+}
+
+# interactive functions
+adb0() {
+	adb -s "$(serial_of $d0)" $@
+}
+
+adb1() {
+	adb -s "$(serial_of $d1)" $@
+}
+
+ping() {
+	echo -e "${Y}[TEST-DATA] ${G}$1${Y} tries to ping ${G}$2${Y} ${NC}"
+	adb -s "$(serial_of "$1")" shell ping -c 3 "$2"
+}
+
+go_to_homescreen() {
+	adb -s "$(serial_of "$d0")" shell input keyevent "$KEYCODE_HOME"
+	adb -s "$(serial_of "$d1")" shell input keyevent "$KEYCODE_HOME"
+}
+
+# unlock_device() expects that there is no password or pattern to unlock the phone.
+# (A straight swipe from bottom to center should unlock the phone.)
+unlock_device() {
+	if [ $# -ne 1 ]; then
+		echo
+		echo -e "${R}[ERROR] You must specify which device (\$d0||\$d1) should be unlocked!"
+		echo
+		return 1
+	fi
+
+	screen_res="$(adb -s $(serial_of $1) shell dumpsys display | grep deviceWidth \
+		| awk -F"deviceWidth=" '{print $2}' | head -n 1)"
+
+	width="$(echo $screen_res | cut -d ',' -f1)"
+	height="$(echo $screen_res | cut -d '=' -f2 | cut -d '}' -f1)"
+
+	# swipe coordinates - from bottom to center
+	x=$((width/2))
+	y1=$((height-20))
+	y2=$((height/2))
+
+	adb -s "$(serial_of $1)" shell input keyevent "$KEYCODE_POWER"
+	sleep 1
+	adb -s "$(serial_of $1)" shell input swipe "$x" "$y1" "$x" "$y2"
+}
+
+# check if config file is passed or user requests help?
+if [ "$1" = "-c" ]; then
+	# simply export ASCENT_CONFIG. sanity() will take care about wrong configs.
+	export ASCENT_CONFIG="$2"
+	# cut off first two arguments to simply continue script
+	shift 2
+
+elif [ "$1" = "-h" ] || [[ "$1" == *"help"* ]]; then
 	print_help
 	return 0
 fi
 
 if [ $# -gt 0 ]; then
-
 	# Enable error code evaluation for test_ascent.sh
 	if [ "$1" = "testing" ]; then
 		sanity
 		exit $?
 	else
-		# Calling normal sanity check otherwise
 		sanity
 	fi
 
-	# dryrun is used by test_ascent.sh to avoid calling print_help()
 	if [ $? -eq 0 ]; then
-		for var in "$@"; do
-				$var
-			if [ $? -gt 0 ]; then print_help; fi
+		# executing each test-case/suite sequentially
+		for test in "$@"; do
+				$test
+			# abort if passed test-case/suite i.e. command, could not be found
+			if [ $? -gt 0 ]; then
+				print_help
+				echo
+				echo "${R} [ERROR] test-case/suite: \"$test\" is not available"
+				echo
+				exit 1
+			fi
 		done
 	fi
 else
-	# interactive mode (only when sourced)
+	# interactive mode (only when sourced or no argument has been passed)
 	print_help
 	sanity
 fi
